### PR TITLE
Convert provider_region validation to a proc

### PR DESCRIPTION
**Pull request by agrare**

### CODE REVIEW

**Comment by Fryguy** [comment]
The provider regions being in the :in caused us to eager load the oci gem, which we want to avoid if the user never uses oci.  This change effectively delay loads it.

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
Should this be morphy/yes? also?

**Comment by Fryguy** [comment]
Backported to `najdorf` in commit 56ae1165aa305b730330fde002bac89a9b138fe0.

```text
commit 56ae1165aa305b730330fde002bac89a9b138fe0
Author: Jason Frey <fryguy9@gmail.com>
Date:   Thu Mar 10 18:03:47 2022 -0500

    Merge pull request #50 from agrare/delay_load_validates_provider_region
    
    Convert provider_region validation to a proc
    
    (cherry picked from commit 90f34941b8674b37cad208cf3e68c59ab13061fa)
```

**Comment by agrare** [comment]
> Should this be morphy/yes? also?

morphy didn't pull regions from the OCI gem so while it would work on morphy it isn't required to prevent loading oci on startup

**Pull request merged**
